### ISSUE TITLE
Only listing operations have correct input parameter generated

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/data-node-client#2]
https://github.com/nlpsandbox/data-node-client/blob/main/swagger_client/api/dataset_api.py#L225

**Comment by thomasyu888** [comment]
My initial hypothesis is that it doesn't read these correctly: https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/openapi/data-node/paths/datasets%40%7BdatasetId%7D.yaml. 

There is actually a way to include all of these in one yaml without the `@`

**Comment by tschaffter** [comment]
See https://github.com/nlpsandbox/data-node-client/issues/5#issuecomment-737354842
