### ISSUE TITLE
Response type seems to be incorrect

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/data-node-client#5]
```
import datanodeclient
api_cilent = datanodeclient.ApiClient()
api_cilent.configuration.host = "http://10.23.55.45:8080/api/v1"
dataset_api = datanodeclient.DatasetApi(api_cilent)
dataset_api.get_dataset("awesome-dataset")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-dffcbe494849> in <module>
----> 1 dataset_api.get_dataset("awesome-dataset")

~/sage/data-node-client/datanodeclient/api/dataset_api.py in get_dataset(self, dataset_id, **kwargs)
    250             return self.get_dataset_with_http_info(dataset_id, **kwargs)  # noqa: E501
    251         else:
--> 252             (data) = self.get_dataset_with_http_info(dataset_id, **kwargs)  # noqa: E501
    253             return data
    254 

~/sage/data-node-client/datanodeclient/api/dataset_api.py in get_dataset_with_http_info(self, dataset_id, **kwargs)
    324             _preload_content=params.get('_preload_content', True),
    325             _request_timeout=params.get('_request_timeout'),
--> 326             collection_formats=collection_formats)
    327 
    328     def list_datasets(self, **kwargs):  # noqa: E501

~/sage/data-node-client/datanodeclient/api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, async_req, _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    319                                    response_type, auth_settings,
    320                                    _return_http_data_only, collection_formats,
--> 321                                    _preload_content, _request_timeout)
    322         else:
    323             thread = self.pool.apply_async(self.__call_api, (resource_path,

~/sage/data-node-client/datanodeclient/api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    158             # deserialize response data
    159             if response_type:
--> 160                 return_data = self.deserialize(response_data, response_type)
    161             else:
    162                 return_data = None

~/sage/data-node-client/datanodeclient/api_client.py in deserialize(self, response, response_type)
    230             data = response.data
    231 
--> 232         return self.__deserialize(data, response_type)
    233 
    234     def __deserialize(self, data, klass):

~/sage/data-node-client/datanodeclient/api_client.py in __deserialize(self, data, klass)
    258                 klass = self.NATIVE_TYPES_MAPPING[klass]
    259             else:
--> 260                 klass = getattr(datanodeclient.models, klass)
    261 
    262         if klass in self.PRIMITIVE_TYPES:

AttributeError: module 'datanodeclient.models' has no attribute 'DatasetsdatasetId'
```

**Comment by thomasyu888** [comment]
https://github.com/nlpsandbox/data-node-client/blob/main/datanodeclient/api/dataset_api.py#L225

**Comment by thomasyu888** [comment]
My guess is that the responsetype is tied to the path..  So if the path is `fhirStores@{fhirStoreId}.yaml` it will be `FhirStoresfhirStoreId`.  which is incorrect. 

I could manually fix these, but it could be a bit of work.   An alternative is to refactor the schemas

**Comment by thomasyu888** [comment]
Further investigation leads me to believe that this is the cause:

https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/openapi/data-node/openapi.yaml#L49

**Comment by thomasyu888** [comment]
Furthermore, when I changed these lines in the openapi.yaml

```
  /datasets:
    $ref: 'paths/datasets@{main}.yaml'
```

The response type became:  `Datasetsmain`

I also tested by renaming `datasets@{datasetId}.yaml` to `datasets_datasetId.yaml` and the response type was correct.

**Comment by tschaffter** [comment]
You must use the combined OpenAPI spec, not the split specification, as input to the code generator. You can either grab one of the version published on GitHub pages or build it. I recommend that we use the edge version, which is the version automatically built after a push to the branch `develop`.

https://nlpsandbox.github.io/nlpsandbox-schemas/data-node/edge/docs/  => click on the button "Download" on the top of the page to download the spec in JSON format, or use one of the following links:

https://nlpsandbox.github.io/nlpsandbox-schemas/data-node/edge/openapi.json
https://nlpsandbox.github.io/nlpsandbox-schemas/data-node/edge/openapi.yaml

**Comment by tschaffter** [comment]
Alternatively, here is how to build the OpenAPI spec for the data node: 

From the root directory of the schemas project:
`npm run build --entrypoint=openapi/data-node/openapi.yaml`

**Comment by tschaffter** [comment]
I quickly created a client codebase for the data node: https://github.com/nlpsandbox/data-node-client/tree/main/alternative

The command I used is in the file package.json
This codebase was generated using the combined spec of the data node, which is visible in the file dist.yaml
The codebase can be (re)generated using npm run generate:client dist.yaml

**Comment by thomasyu888** [comment]
Thanks @tschaffter!
